Insert::

Send **-=:coffee:Reino do café:coffee:=-**
Sleep 110
Send {LShift Down}
Sleep 110
Send {Enter}
Sleep 110
Send {LShift Up}
Send -É um servidor feito para jogar e fazer amigos.
Sleep 110
Send {LShift Down}
Sleep 110
Send {Enter}
Sleep 110
Send {LShift Up}
Send -Temos varios chats de voz e mensagem.
Sleep 110
Send {LShift Down}
Sleep 110
Send {Enter}
Sleep 110
Send {LShift Up}
Send -Sistema de registro automático com bots
Sleep 110
Send {LShift Down}
Sleep 110
Send {Enter}
Sleep 110
Send {LShift Up}
Send -Eventos.
Sleep 110
Send {LShift Down}
Sleep 110
Send {Enter}
Sleep 110
Send {LShift Up}
Send -Sorteios.
Send {LShift Up}
Sleep 110
Send {LShift Down}
Sleep 110
Send {Enter}
Send {Enter}
Sleep 110
Send {LShift Up}

Send Link :link: https://discord.gg/nzJeABvszM
Sleep 110
Send {LShift Down}
Sleep 110
Send {Enter}
Send {Enter}
Sleep 110
Send {LShift Up}

Send Ping: ||@everyone ||
Sleep 110
Send {Enter}

